### ISSUE TITLE
second column online is missing

### ISSUE THREAD

**Issue by alealvisi** [van4two/van4two.github.io#27] opened 2022-09-03 07:12 UTC
the text of the second column is at the end of the first

**Comment by cooked** [comment] 2022-10-02 18:06
see norway / bessegen as an example

**Comment by cooked** [comment] 2022-10-02 21:59
@alealvisi this was due to the css file not being picked up... which was caused by the whole site being published at _site instead of root
this has been fixed by correcting the "publishing" workflow action

with the right path now in place the css style is picked up correctly and the columns and all other styles are now ok

**Closed by cooked** 2022-10-02 21:59 UTC
Labels: bug
